# Generated by Django 5.2.4 on 2025-08-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_weekday_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='time',
        ),
        migrations.AddField(
            model_name='weekday',
            name='time_close',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekday',
            name='time_open',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
