# Generated by Django 5.2.4 on 2025-08-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_weekday_time_weekday_time_close_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekday',
            old_name='day',
            new_name='day_close',
        ),
        migrations.AddField(
            model_name='weekday',
            name='day_open',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
