# Generated by Django 5.2.4 on 2025-08-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categoryevent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
