# Generated by Django 5.2.4 on 2025-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
