# Generated by Django 5.2.4 on 2025-08-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_categorynewsletter_slug_alter_newsletter_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorynewsletter',
            name='slug',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
