# Generated by Django 5.2.4 on 2025-08-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='score',
            field=models.CharField(max_length=4),
        ),
    ]
