# Generated by Django 5.2.4 on 2025-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_comment_category_description_category_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about_team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='about_kitchen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
