# Generated by Django 5.2.4 on 2025-08-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_about_team_menu_about_kitchen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='about_kitchen',
        ),
        migrations.AddField(
            model_name='category',
            name='about_kitchen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
