# Generated by Django 5.2.4 on 2025-08-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_teammember_description'),
        ('menu', '0004_remove_menu_about_kitchen_category_about_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='about_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.teammember'),
        ),
    ]
