# Generated by Django 5.2.4 on 2025-08-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='about_team',
        ),
        migrations.RemoveField(
            model_name='category',
            name='news_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
