# Generated by Django 5.2.4 on 2025-08-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_category_about_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
