# Generated by Django 5.2.4 on 2025-08-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menu_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
