# Generated by Django 5.2.4 on 2025-08-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menu_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'وعده', 'verbose_name_plural': 'دسته ها'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='وعده'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menu/', verbose_name='عکس غذا'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت اصلی'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='score',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='views',
            field=models.IntegerField(verbose_name='بازدید'),
        ),
    ]
