# Generated by Django 5.2.4 on 2025-08-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثل: میز 1، VIP-2', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('location', models.CharField(blank=True, help_text='داخل سالن، تراس و ...', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(help_text='مثلاً 1 یا 2 ساعت بعد از شروع')),
                ('service_type', models.CharField(choices=[('dine_in', 'صرف در رستوران'), ('take_away', 'بیرون\u200cبر')], default='dine_in', max_length=20)),
                ('address', models.TextField(blank=True, help_text='برای بیرون\u200cبر (اختیاری)')),
                ('note', models.TextField(blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservation.diningtable')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation.food')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservation.reservation')),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_time', 'end_time'], name='reservation_start_t_9726a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationitem',
            unique_together={('reservation', 'food')},
        ),
    ]
